# A full list of RPC endpoints can be found here:
#
#  https://blastapi.io/public-api/starknet
#
[sncast.default]
# url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
url = "http://127.0.0.1:5050/rpc"

