[package]
name = "src"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
sncast_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.20.1" }
chainlink = { path = "../../../../contracts" }
aggregator_consumer = { path = "../" }

[lib]
casm = true

[[target.starknet-contract]]
casm = true
build-external-contracts = [
  "chainlink::emergency::sequencer_uptime_feed::SequencerUptimeFeed",
  "chainlink::ocr2::mocks::mock_aggregator::MockAggregator",
  "aggregator_consumer::ocr2::consumer::AggregatorConsumer"
]

# [profile.devnet]
# url = "http://127.0.0.1:5050/rpc"
# accounts-file = "$DEVNET_ACCOUNTS_FILE"
# account = "$DEVNET_ACCOUNT_NAME"
# hex-format = true
#
# [profile.testnet]
# url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
# accounts-file = "$TESTNET_ACCOUNTS_FILE"
# account = "$TESTNET_ACCOUNT_NAME"
# hex-format = true
#
